### ISSUE TITLE
yolov8 Model Transformation

### ISSUE THREAD

**Issue by jef-way** [lanseria/yolov8-tfjs-vue-webrtc-demo#1]
I would like to ask how your YOLOv8 model converts to tfjs. I trained a model myself, but the teacher reported an error when converting to tfjs？

**Comment by lanseria** [comment]
@jef-way I'll go back and look for it tonight

**Comment by jef-way** [comment]
okay, thank you

**Comment by lanseria** [comment]
@jef-way I have found the relevant  and can give it a try. https://github.com/Hyuto/yolov8-tfjs

**Comment by jef-way** [comment]
Is the model in your project directly used in this project?

**Comment by lanseria** [comment]
> Is the model in your project directly used in this project?

对

**Comment by jef-way** [comment]
thank you
